# PyTorch Basics For Reference.

## Tensors

Tensors are specialized data structures which are very similar to arrays and matrices. In PyTorch, tensors are used to encode model's inputs, outputs, and parameters.

Tensors are similar to NumPy’s ndarrays, but they have a superpower. Tensors can also be used on a GPU to accelerate computing. Tensors are also optimized for automatic differentiation (computing gradients) which is useful in training neural networks.

In [2]:
import torch
import numpy as np

## Initializing a Tensor

Tensors can be initialized in multiple ways.

### Directly from the data

In [3]:
data = [[10, 20], [30, 40], [50, 60]]

x_data = torch.tensor(data)
x_data

tensor([[10, 20],
        [30, 40],
        [50, 60]])

### From NumPy array

Tensor can be created from a NumPy array and vice versa.

In [4]:
np_array = np.array(data)
x_np = torch.from_numpy(np_array)
x_np

tensor([[10, 20],
        [30, 40],
        [50, 60]])

In [5]:
np_array2 = x_data.numpy()
np_array2

array([[10, 20],
       [30, 40],
       [50, 60]])

### From another tensor
Tensor can be created from another tensor and retains the properties of the input tensor unless explicitly overridden.

In [6]:
x_ones = torch.ones_like(x_data)
x_ones

tensor([[1, 1],
        [1, 1],
        [1, 1]])

In [7]:
x_rand = torch.rand_like(x_data, dtype=torch.float)
x_rand

tensor([[0.0133, 0.0150],
        [0.7236, 0.6584],
        [0.1728, 0.3560]])

## Understanding shape

Shape of a tensor is the number of elements in each dimension. PyTorch tensors have the same shape as NumPy arrays.

In [8]:
shape = (2, 3,)
rand_tensor = torch.rand(shape)
ones_tensor = torch.ones(shape)
zeros_tensor = torch.zeros(shape)

print(f'Random Tensor: \n {rand_tensor} \n')
print(f'Ones Tensor: \n {ones_tensor} \n')
print(f'Zeros Tensor: \n {zeros_tensor}')

Random Tensor: 
 tensor([[0.0499, 0.1718, 0.6330],
        [0.2087, 0.9628, 0.7508]]) 

Ones Tensor: 
 tensor([[1., 1., 1.],
        [1., 1., 1.]]) 

Zeros Tensor: 
 tensor([[0., 0., 0.],
        [0., 0., 0.]])


## Attributes of a Tensor

Apart from shape, there are other attributes of the tensor e.g. datatype, device on which they are stored etc.

In [9]:
tensor = torch.rand(2, 3)
print(f'Shape of tensor: {tensor.shape}')
print(f'Datatype of tensor: {tensor.dtype}')
print(f'Device tensor is stored on: {tensor.device}')

Shape of tensor: torch.Size([2, 3])
Datatype of tensor: torch.float32
Device tensor is stored on: cpu


## Operations on Tensors
### Torch stack vs torch cat

`torch.stack` concatenates sequence of tensors along a new dimension whereas `torch.cat` concatenates sequence of tensors in the same dimension.


In [11]:
t1 = torch.cat([tensor, tensor, tensor], dim=1)
print(f't1: \n {t1} \n')

t2 = torch.stack([tensor, tensor, tensor], dim=1)
print(f't2: \n {t2} \n')

t1: 
 tensor([[0.4216, 0.5183, 0.0112, 0.4216, 0.5183, 0.0112, 0.4216, 0.5183, 0.0112],
        [0.7111, 0.3705, 0.1031, 0.7111, 0.3705, 0.1031, 0.7111, 0.3705, 0.1031]]) 

t2: 
 tensor([[[0.4216, 0.5183, 0.0112],
         [0.4216, 0.5183, 0.0112],
         [0.4216, 0.5183, 0.0112]],

        [[0.7111, 0.3705, 0.1031],
         [0.7111, 0.3705, 0.1031],
         [0.7111, 0.3705, 0.1031]]]) 

